# Generated by Django 4.2.30 on 2026-04-26 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_score', models.FloatField(default=0)),
                ('answer_quality_avg', models.FloatField(default=0)),
                ('confidence_avg', models.FloatField(default=0)),
                ('communication_avg', models.FloatField(default=0)),
                ('overall_feedback', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='interviews.interviewsession')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_score', models.FloatField(default=0)),
                ('confidence_score', models.FloatField(default=0)),
                ('communication_score', models.FloatField(default=0)),
                ('overall_score', models.FloatField(default=0)),
                ('strengths', models.JSONField(default=list)),
                ('weaknesses', models.JSONField(default=list)),
                ('suggestions', models.JSONField(default=list)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('response', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='interviews.interviewresponse')),
            ],
        ),
    ]
